### ISSUE TITLE
Ability to map the current collection to multiple namespaces and endpoints

### ISSUE THREAD

**Issue by seulsale** [IBM/operator-collection-sdk-vscode-extension#11]
## Feature Request
Add support to install an operator collection to one or more endpoint and namespaces.

#### Describe the problem you need a feature to resolve.
Right now there is only support for installing the suboperator collection to one namespace and endpoint, which is useful but doesn't cover all use cases supported compared to the Cloud Broker UI. 
I've been working in a fix/feature that involves installing to multiple namespaces and endpoints and thus I have been using only the Broker UI. 

#### Describe the solution you'd like.
Being able to pass more than one namespace and endpoint as parameters to the `ocsdk-operator-create` command or provide a config file like the one below.  

```yaml
endpoints:
  - name: test-1
    host: test-1.com
  - name: test2
    host: test2.internal.com

namespaces:
  - name: ns-seulsale
    endpoints:
      - test-1
      - test2
  - name: ns-seulsale2
    endpoints:
      - test-1
      - test2
credentials: personal
```
